### ISSUE TITLE
build.sh warning: cannot create directory `/qemu/staging/src': File exists

### ISSUE THREAD

**Issue by jcard0na** [cozybit/distro11s#1]
Building libnl
mkdir: cannot create directory `/mnt/sdd/distro11s/out/qemu/staging/src': File exists
Building iw
mkdir: cannot create directory`/mnt/sdd/distro11s/out/qemu/staging/src': File exists
Building authsae
mkdir: cannot create directory `/mnt/sdd/distro11s/out/qemu/staging/src': File exists

**Comment by ashokrajnagarajan** [comment]
Fixed with the commit f39a92004a5eee1732311694cc0693cb130e1b59
